---
title: "Untitled"
author: "Rodrigo Dal Ben"
date: "Apr. 09, 2022"
output: html_document
---

Extra code: 

```{r}
# experiment 1: performance plot
plot_perf_experiment1 <- 
  data_summ_plot %>% 
  filter(experiment == 1,
         trial_type %in% c("test ws", "test cswl")) %>% 
  ggplot(aes(x = speech_version, y = avg_resp, fill = trial_type)) +
  geom_violin(position = position_dodge(0.8), alpha = 0.6, size = 0.3) +
  geom_dotplot(binaxis = "y", stackdir = "center", dotsize = 0.5, position = position_dodge(0.8), alpha = 0.6) +
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = 0.8)) + # boot CIs
  scale_fill_manual(values = cb_pal, name = "Task", labels = c("Segmentation", "Mapping")) +
  coord_cartesian(ylim = c(0, 1)) +
  scale_y_continuous(breaks = seq(0, 1, 0.2)) +
  scale_x_discrete(labels = c("Balanced", "Aligned", "Conflict")) +
  annotate("segment", x = 0.65, xend = 1, y = 0.5, yend = 0.5, linetype = "dashed") + # chance level ws
  annotate("segment", x = 1.65, xend = 2, y = 0.5, yend = 0.5, linetype = "dashed") + 
  annotate("segment", x = 2.65, xend = 3, y = 0.5, yend = 0.5, linetype = "dashed") + 
  annotate("segment", x = 1, xend = 1.35, y = 0.25, yend = 0.25, linetype = "dashed") + # chance level cswl
  annotate("segment", x = 2, xend = 2.35, y = 0.25, yend = 0.25, linetype = "dashed") +
  annotate("segment", x = 3, xend = 3.35, y = 0.25, yend = 0.25, linetype = "dashed") +
  labs(title = "Experiment 1", y = "Proportion of correct selection", x = "Speech version") + 
  theme_classic(base_size = 10) +
  theme(legend.title.align = 0.5)

plot_perf_experiment1

#ggsave(plot = plot_perf_experiment1, 
#       filename = here("03_output_graphics/plot_perf_experiment1.png"), 
#       width = 12, height = 8, units = "cm", dpi = 300)

# experiment 2: performance plot
plot_perf_experiment2 <- 
  data_summ_plot %>% 
  filter(experiment == 2,
         trial_type %in% c("test ws", "test cswl")) %>% 
  ggplot(aes(x = speech_version, y = avg_resp, fill = trial_type)) +
  geom_violin(position = position_dodge(0.8), alpha = 0.6, size = 0.3) +
  geom_dotplot(binaxis = "y", stackdir = "center", dotsize = 0.5, position = position_dodge(0.8), alpha = 0.6) +
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = 0.8)) + # boot CIs
  scale_fill_manual(values = cb_pal, name = "Task", labels = c("Segmentation", "Mapping")) +
  coord_cartesian(ylim = c(0, 1)) +
  scale_y_continuous(breaks = seq(0, 1, 0.2)) +
  scale_x_discrete(labels = "Conflict") +
  annotate("segment", x = 0.65, xend = 1, y = 0.5, yend = 0.5, linetype = "dashed") + # chance level ws
  annotate("segment", x = 1, xend = 1.35, y = 0.25, yend = 0.25, linetype = "dashed") + # chance level cswl
  labs(title = "Experiment 2", y = "Proportion of correct selection", x = "Speech version") + 
  theme_classic(base_size = 10) +
  theme(legend.title.align = 0.5)

plot_perf_experiment2

#ggsave(plot = plot_perf_experiment2, 
#       filename = here("03_output_graphics/plot_perf_experiment2.png"),
#       width = 8, height = 8, units = "cm", dpi = 300)

# cswl comparison joint vs. single

plot_cswl_only <- 
  data_summ_plot_all %>% 
  filter(experiment %in% c("cswl only", "ws + cswl joint"),
         trial_type == "test cswl") %>%
  ggplot(aes(x = speech_version, y = avg_resp, fill = experiment)) +
  geom_violin(position = position_dodge(0.8), alpha = 0.6, size = 0.3) +
  geom_dotplot(binaxis = "y", stackdir = "center", dotsize = 0.5, position = position_dodge(0.8), alpha = 0.4) +
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = 0.8)) + # boot CIs
  scale_fill_manual(values = cb_pal[4:5], name = "Experiment", labels = c("cswl only", "parallel task")) +
  coord_cartesian(ylim = c(0, 1)) +
  scale_y_continuous(breaks = seq(0, 1, 0.2)) +
  scale_x_discrete(labels = c("cswl only", "Parallel -\n Balanced", 
                              "Parallel -\n Aligned", "Parallel -\n Conflict")) +
  annotate("segment", x = 0.5, xend = 4.5, y = 0.25, yend = 0.25, linetype = "dashed") + # chance level cswl
  labs(title = "Cross-situational word learning only \nvs. parallel (ws+cswl) experiment", y = "Proportion of correct selection", x = "Experiment and language version") + 
  theme_classic(base_size = 10) +
  #theme(legend.title.align = 0.5)
  theme(legend.position = "none")

plot_cswl_only

#ggsave(plot = plot_cswl_only, 
#       filename = here("03_output_graphics/plot_cswl_only_comparison.png"),
#       width = 12, height = 8, units = "cm", dpi = 300)

#segmentation by stimuli type
plot_seg_exp2_stimuli_type <- 
  data_summ_plot_audio_type %>% 
  ggplot(aes(x = distractor_audio_type_ws, y = avg_resp, fill = distractor_audio_type_ws)) +
  geom_violin(position = position_dodge(1), alpha = 0.6, size = 0.3) +
  geom_dotplot(binaxis = "y", stackdir = "center", dotsize = 0.5, position = position_dodge(1), alpha = 0.6) +
  #geom_point(position = position_jitterdodge(jitter.width = 0.1, dodge.width = 1), alpha = 0.3) +
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = 1)) + # boot CIs
  scale_fill_manual(values = c("white", cb_pal[3], cb_pal[6])) +
  coord_cartesian(ylim = c(0, 1)) +
  scale_y_continuous(breaks = seq(0, 1, 0.2)) +
  scale_x_discrete(labels = c("Non-word", "Part-word", "Word")) +
  annotate("segment", x = 0.5, xend = 3.5, y = 0.5, yend = 0.5, linetype = "dashed") + # chance level ws
  labs(title = "Experiment 2 - Speech segmentation\n by stimuli type", y = "Proportion of correct evaluation", x = "Stimuli type") + 
  theme_classic(base_size = 10) +
  theme(legend.position = "none",
        axis.ticks.x = element_blank())

plot_seg_exp2_stimuli_type

#ggsave(plot = plot_seg_exp2_stimuli_type, 
#       filename = here("03_output_graphics/plot_seg_type_experiment2.png"),
#       width = 10, height = 8, units = "cm", dpi = 300)

######

# segmentation and self evaluation
plot_corr_seg_eval_exp2 <- 
  data_summ_correlation %>%
  filter(experiment == 2) %>%
  mutate(speech_version_label = case_when(speech_version == "L_conflict" ~ "Conflict")) %>% 
  ggplot(aes(x = `test ws`, y = `self evaluation ws`, color = speech_version)) +
  geom_count(alpha = 0.3) +
  geom_smooth(method = "lm", se = F, color = "dark grey", alpha = 0.3, fullrange = T) +
  #facet_wrap(~ speech_version_label) +
  scale_color_manual(values = cb_pal[3], guide = F) +
  scale_size_area() +
  coord_cartesian(xlim = c(0, 1), ylim = c(0, 1)) +
  labs(title = "Experiment 2 - \nSegmentation and self-evaluation", 
       x = "Proportion of corret segmentation", 
       y = "Self-evaluation") + 
  theme_classic(base_size = 10) +
  theme(legend.title.align = 0.5,
        panel.spacing = unit(0.8, "lines"))

plot_corr_seg_eval_exp2

#ggsave(plot = plot_corr_seg_eval_exp2, 
#       filename = here("03_output_graphics/plot_corr_seg_eval_exp2.png"),
#       width = 8, height = 6, units = "cm", dpi = 300)


# mapping and self evaluation
plot_corr_map_eval_exp2 <- 
  data_summ_correlation %>%
  filter(experiment == 2) %>%
  mutate(speech_version_label = case_when(speech_version == "L_conflict" ~ "Conflict")) %>% 
  ggplot(aes(x = `test cswl`, y = `self evaluation cswl`, color = speech_version)) +
  geom_count(alpha = 0.3) +
  geom_smooth(method = "lm", se = F, color = "dark grey", alpha = 0.3, fullrange = T) +
  #facet_wrap(~ speech_version_label) +
  scale_color_manual(values = cb_pal[3], guide = F) +
  scale_size_area() +
  coord_cartesian(xlim = c(0, 1), ylim = c(0, 1)) +
  labs(title = "Experiment 2 - \nMapping and self-evaluation", 
       x = "Proportion of corret mapping", 
       y = "Self-evaluation") + 
  theme_classic(base_size = 10) +
  theme(legend.title.align = 0.5,
        panel.spacing = unit(0.8, "lines"))

plot_corr_map_eval_exp2

#ggsave(plot = plot_corr_map_eval_exp2, 
#       filename = here("03_output_graphics/plot_corr_map_eval_exp2.png"),
#       width = 8, height = 6, units = "cm", dpi = 300)

# joint, segmentation and mapping
joint_perf_eval_exp2 <- plot_corr_seg_eval_exp2 + (plot_corr_map_eval_exp2 + theme(axis.title.y = element_blank(), axis.text.y = element_blank()))

#ggsave(plot = joint_perf_eval_exp2, 
#       filename = here("03_output_graphics/plot_corr_eval_joint_exp2.png"),
#       width = 15, height = 8, units = "cm", dpi = 300)
```

#### Word Segmentation & Cross-Situational Word Learning

##### Prepare data

```{r prepare data interaction ws cswl}
# temporary sets
temp0 <-
  data_filtered_v2 %>% 
  select(p_n_unique, trial_type, is_correct) %>%
  filter(trial_type %in% c("test ws", "test cswl")) %>% 
  mutate(p_n_unique = p_n_unique + row_number()) %>% 
  pivot_wider(names_from = trial_type, values_from = is_correct) %>% 
  mutate(p_n_unique = p_n_unique - row_number()) %>% 
  unnest() 

temp1 <- 
  tibble(p_n_unique = temp0$p_n_unique, test_ws = temp0$`test ws`) %>% 
  drop_na() %>% 
  group_by(p_n_unique) %>% 
  mutate(i = row_number()) %>% 
  mutate(i = paste(p_n_unique, row_number()))

temp2 <- 
  tibble(p_n_unique = temp0$p_n_unique, test_cswl = temp0$`test cswl`) %>% 
  drop_na() %>% 
  group_by(p_n_unique) %>% 
  mutate(i = paste(p_n_unique, row_number()))

temp3 <- 
  data_filtered_v2 %>% 
  group_by(p_n_unique) %>% 
  slice_head() %>% 
  select(p_n_unique, speech_version, experiment)

temp4 <- 
  left_join(temp1, temp2, by = "i") %>% 
  mutate(p_n_unique = p_n_unique.x) %>% 
  select(-p_n_unique.x, -p_n_unique.y, -i) 

# final set to be used in the model
data_reg_ws_cswl <- left_join(temp4, temp3, by = "p_n_unique")
```

##### Model

```{r interaction ws cswl model}
# experiment 1
## performance on WS as predictor of performance on CSWL
mod_ws_cswl_exp1 <- 
  data_reg_ws_cswl %>% 
  filter(experiment == 1) %>% 
  glmer(test_ws ~ test_cswl:speech_version + (1|p_n_unique),
        family = "binomial",
        data = .
        )

## performance on CSWL as predictor of performance on WS
mod_cswl_ws_exp1 <- 
  data_reg_ws_cswl %>% 
  filter(experiment == 1) %>% 
  glmer(test_cswl ~ test_ws:speech_version + (1|p_n_unique),
        family = "binomial",
        data = .
        )

sjPlot::tab_model(mod_ws_cswl_exp1, mod_cswl_ws_exp1, 
                  show.p = F,
                  title = "Experiment 1 - WS & CSWL: WS as predictor of CSWL, and CSWL as predictor of WS")#, 
                  #file = here("03_output_graphics/mod_freq_ws_map_exp1.doc"))

# experiment 2
## performance on WS as predictor of performance on CSWL
mod_ws_cswl_exp2 <- 
  data_reg_ws_cswl %>% 
  filter(experiment == 2) %>% 
  glmer(test_ws ~ test_cswl + (1|p_n_unique),
        family = "binomial",
        data = .
        )

## performance on CSWL as predictor of performance on WS
mod_cswl_ws_exp2 <- 
  data_reg_ws_cswl %>% 
  filter(experiment == 2) %>% 
  glmer(test_cswl ~ test_ws + (1|p_n_unique),
        family = "binomial",
        data = .
        )

sjPlot::tab_model(mod_ws_cswl_exp2, mod_cswl_ws_exp2, 
                  show.p = F,
                  title = "Experiment 2 - WS & CSWL: WS as predictor of CSWL, and CSWL as predictor of WS")#, 
                  #file = here("03_output_graphics/mod_freq_ws_map_exp2.doc"))
```


